add last round of code checks before deployment

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -12,6 +12,29 @@ jobs:
     - name: Checkout "${{ github.repository }}"
       uses: actions/checkout@v3
 
+    - name: Set up Node (stable)
+      uses: actions/setup-node@v4
+      with:
+        node-version: 20.16
+
+    - name: Install dependencies
+      run:  |
+        cd frontend && npm ci
+
+    - name: Last linting check before deployment
+      run: npm run lint
+
+    - name: Last tests before deployment
+      run: npm run test
+
+    - name: Verify Build before deployment
+      run: |
+        npm run build:swc
+        if [ ! -f "backend/dist/src/main.js" ]; then
+          echo "Build failed: main.js not found!"
+          exit 1
+        fi
+
     - name: Install SSH Key
       uses: webfactory/ssh-agent@v0.7.0
       with:
